/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingId = IDL.Nat;
export const RetrievalStatus = IDL.Variant({
  'closed' : IDL.Null,
  'reviewing' : IDL.Null,
  'documentationComplete' : IDL.Null,
  'arrived' : IDL.Null,
  'traveling' : IDL.Null,
  'requestReceived' : IDL.Null,
  'finished' : IDL.Null,
  'inProgress' : IDL.Null,
  'coordinatorAssigned' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const Timestamp = IDL.Nat;
export const UserId = IDL.Principal;
export const RetrievalType = IDL.Variant({
  'separation' : IDL.Null,
  'emergency' : IDL.Null,
  'propertyExchange' : IDL.Null,
  'storage' : IDL.Null,
  'familyConflict' : IDL.Null,
  'breakup' : IDL.Null,
  'roommate' : IDL.Null,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'city' : IDL.Text,
  'unit' : IDL.Opt(IDL.Text),
  'gateCode' : IDL.Opt(IDL.Text),
  'specialInstructions' : IDL.Opt(IDL.Text),
  'state' : IDL.Text,
});
export const SafetyAssessment = IDL.Record({
  'potentialThreats' : IDL.Bool,
  'restrainingOrder' : IDL.Bool,
  'petsPresent' : IDL.Bool,
  'notes' : IDL.Opt(IDL.Text),
  'policeInvolvement' : IDL.Bool,
  'childrenPresent' : IDL.Bool,
  'historyOfConflict' : IDL.Bool,
  'weaponsConcern' : IDL.Bool,
});
export const Booking = IDL.Record({
  'id' : BookingId,
  'status' : RetrievalStatus,
  'paymentStatus' : PaymentStatus,
  'scheduledDate' : Timestamp,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'retrievalType' : RetrievalType,
  'updatedAt' : Timestamp,
  'pickupAddress' : Address,
  'totalAmount' : IDL.Nat,
  'safetyAssessment' : SafetyAssessment,
});
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});
export const CoordinatorLocation = IDL.Record({
  'bookingId' : BookingId,
  'updatedAt' : Timestamp,
  'location' : Location,
});
export const DocumentId = IDL.Nat;
export const DocumentType = IDL.Variant({
  'pdf' : IDL.Null,
  'report' : IDL.Null,
  'signature' : IDL.Null,
  'receipt' : IDL.Null,
  'other' : IDL.Null,
  'video' : IDL.Null,
  'photo' : IDL.Null,
});
export const Document = IDL.Record({
  'id' : DocumentId,
  'url' : IDL.Text,
  'bookingId' : BookingId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'docType' : DocumentType,
});
export const InventoryItemId = IDL.Nat;
export const ItemStatus = IDL.Variant({
  'damaged' : IDL.Null,
  'disputed' : IDL.Null,
  'pending' : IDL.Null,
  'notRetrieved' : IDL.Null,
  'retrieved' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const ItemCondition = IDL.Variant({
  'damaged' : IDL.Null,
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'poor' : IDL.Null,
  'excellent' : IDL.Null,
});
export const InventoryItem = IDL.Record({
  'id' : InventoryItemId,
  'status' : ItemStatus,
  'photoUrls' : IDL.Vec(IDL.Text),
  'bookingId' : BookingId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'estimatedValue' : IDL.Opt(IDL.Nat),
  'priority' : Priority,
  'condition' : ItemCondition,
});
export const MessageId = IDL.Nat;
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'staff' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'bookingId' : BookingId,
  'createdAt' : Timestamp,
  'senderRole' : Role,
  'attachments' : IDL.Vec(IDL.Text),
  'senderId' : UserId,
});
export const User = IDL.Record({
  'id' : UserId,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const ApiError = IDL.Variant({
  'notFound' : IDL.Null,
  'internalError' : IDL.Text,
  'unauthorized' : IDL.Null,
  'badRequest' : IDL.Text,
});
export const Result_9 = IDL.Variant({ 'ok' : Document, 'err' : ApiError });
export const Result = IDL.Variant({ 'ok' : InventoryItem, 'err' : ApiError });
export const Result_8 = IDL.Variant({ 'ok' : Message, 'err' : ApiError });
export const Result_2 = IDL.Variant({ 'ok' : Booking, 'err' : ApiError });
export const Result_1 = IDL.Variant({
  'ok' : CoordinatorLocation,
  'err' : ApiError,
});
export const Result_7 = IDL.Variant({
  'ok' : IDL.Vec(Document),
  'err' : ApiError,
});
export const Result_6 = IDL.Variant({
  'ok' : IDL.Vec(InventoryItem),
  'err' : ApiError,
});
export const Result_5 = IDL.Variant({
  'ok' : IDL.Vec(Message),
  'err' : ApiError,
});
export const Result_4 = IDL.Variant({
  'ok' : IDL.Vec(Booking),
  'err' : ApiError,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Result_3 = IDL.Variant({ 'ok' : UserProfile, 'err' : ApiError });
export const LoginInput = IDL.Record({
  'password' : IDL.Text,
  'email' : IDL.Text,
});
export const RegisterInput = IDL.Record({
  'password' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  '__bookings' : IDL.Func(
      [IDL.Opt(BookingId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(BookingId, Booking))],
      ['query'],
    ),
  '__coordinatorLocations' : IDL.Func(
      [IDL.Opt(BookingId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(BookingId, CoordinatorLocation))],
      ['query'],
    ),
  '__documents' : IDL.Func(
      [IDL.Opt(DocumentId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(DocumentId, Document))],
      ['query'],
    ),
  '__inventoryItems' : IDL.Func(
      [IDL.Opt(InventoryItemId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(InventoryItemId, InventoryItem))],
      ['query'],
    ),
  '__messages' : IDL.Func(
      [IDL.Opt(MessageId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(MessageId, Message))],
      ['query'],
    ),
  '__nextBookingId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextDocumentId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextInventoryItemId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextMessageId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextUserId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__users' : IDL.Func(
      [IDL.Opt(UserId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(UserId, User))],
      ['query'],
    ),
  'addDocument' : IDL.Func(
      [BookingId, DocumentType, IDL.Text, IDL.Text],
      [Result_9],
      [],
    ),
  'addInventoryItem' : IDL.Func(
      [
        BookingId,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        Priority,
      ],
      [Result],
      [],
    ),
  'addMessage' : IDL.Func(
      [BookingId, IDL.Text, IDL.Vec(IDL.Text)],
      [Result_8],
      [],
    ),
  'cancelBooking' : IDL.Func([BookingId], [Result_2], []),
  'createBooking' : IDL.Func(
      [RetrievalType, Address, SafetyAssessment, Timestamp, IDL.Nat],
      [Result_2],
      [],
    ),
  'getBooking' : IDL.Func([BookingId], [Result_2], ['query']),
  'getCoordinatorLocation' : IDL.Func([BookingId], [Result_1], ['query']),
  'getDocuments' : IDL.Func([BookingId], [Result_7], ['query']),
  'getInventoryItems' : IDL.Func([BookingId], [Result_6], ['query']),
  'getMessages' : IDL.Func([BookingId], [Result_5], ['query']),
  'getMyBookings' : IDL.Func([], [Result_4], ['query']),
  'getUserProfile' : IDL.Func([], [Result_3], ['query']),
  'listBookings' : IDL.Func([], [Result_4], ['query']),
  'loginUser' : IDL.Func([LoginInput], [Result_3], []),
  'registerUser' : IDL.Func([RegisterInput], [Result_3], []),
  'updateBookingStatus' : IDL.Func(
      [BookingId, RetrievalStatus],
      [Result_2],
      [],
    ),
  'updateCoordinatorLocation' : IDL.Func([BookingId, Location], [Result_1], []),
  'updateInventoryItem' : IDL.Func(
      [
        InventoryItemId,
        IDL.Record({
          'status' : IDL.Opt(ItemStatus),
          'photoUrls' : IDL.Opt(IDL.Vec(IDL.Text)),
          'name' : IDL.Opt(IDL.Text),
          'description' : IDL.Opt(IDL.Text),
          'notes' : IDL.Opt(IDL.Text),
          'estimatedValue' : IDL.Opt(IDL.Nat),
          'priority' : IDL.Opt(Priority),
          'condition' : IDL.Opt(ItemCondition),
        }),
      ],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingId = IDL.Nat;
  const RetrievalStatus = IDL.Variant({
    'closed' : IDL.Null,
    'reviewing' : IDL.Null,
    'documentationComplete' : IDL.Null,
    'arrived' : IDL.Null,
    'traveling' : IDL.Null,
    'requestReceived' : IDL.Null,
    'finished' : IDL.Null,
    'inProgress' : IDL.Null,
    'coordinatorAssigned' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Timestamp = IDL.Nat;
  const UserId = IDL.Principal;
  const RetrievalType = IDL.Variant({
    'separation' : IDL.Null,
    'emergency' : IDL.Null,
    'propertyExchange' : IDL.Null,
    'storage' : IDL.Null,
    'familyConflict' : IDL.Null,
    'breakup' : IDL.Null,
    'roommate' : IDL.Null,
  });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'city' : IDL.Text,
    'unit' : IDL.Opt(IDL.Text),
    'gateCode' : IDL.Opt(IDL.Text),
    'specialInstructions' : IDL.Opt(IDL.Text),
    'state' : IDL.Text,
  });
  const SafetyAssessment = IDL.Record({
    'potentialThreats' : IDL.Bool,
    'restrainingOrder' : IDL.Bool,
    'petsPresent' : IDL.Bool,
    'notes' : IDL.Opt(IDL.Text),
    'policeInvolvement' : IDL.Bool,
    'childrenPresent' : IDL.Bool,
    'historyOfConflict' : IDL.Bool,
    'weaponsConcern' : IDL.Bool,
  });
  const Booking = IDL.Record({
    'id' : BookingId,
    'status' : RetrievalStatus,
    'paymentStatus' : PaymentStatus,
    'scheduledDate' : Timestamp,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'retrievalType' : RetrievalType,
    'updatedAt' : Timestamp,
    'pickupAddress' : Address,
    'totalAmount' : IDL.Nat,
    'safetyAssessment' : SafetyAssessment,
  });
  const Location = IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 });
  const CoordinatorLocation = IDL.Record({
    'bookingId' : BookingId,
    'updatedAt' : Timestamp,
    'location' : Location,
  });
  const DocumentId = IDL.Nat;
  const DocumentType = IDL.Variant({
    'pdf' : IDL.Null,
    'report' : IDL.Null,
    'signature' : IDL.Null,
    'receipt' : IDL.Null,
    'other' : IDL.Null,
    'video' : IDL.Null,
    'photo' : IDL.Null,
  });
  const Document = IDL.Record({
    'id' : DocumentId,
    'url' : IDL.Text,
    'bookingId' : BookingId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'docType' : DocumentType,
  });
  const InventoryItemId = IDL.Nat;
  const ItemStatus = IDL.Variant({
    'damaged' : IDL.Null,
    'disputed' : IDL.Null,
    'pending' : IDL.Null,
    'notRetrieved' : IDL.Null,
    'retrieved' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ItemCondition = IDL.Variant({
    'damaged' : IDL.Null,
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
    'excellent' : IDL.Null,
  });
  const InventoryItem = IDL.Record({
    'id' : InventoryItemId,
    'status' : ItemStatus,
    'photoUrls' : IDL.Vec(IDL.Text),
    'bookingId' : BookingId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'estimatedValue' : IDL.Opt(IDL.Nat),
    'priority' : Priority,
    'condition' : ItemCondition,
  });
  const MessageId = IDL.Nat;
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'staff' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'bookingId' : BookingId,
    'createdAt' : Timestamp,
    'senderRole' : Role,
    'attachments' : IDL.Vec(IDL.Text),
    'senderId' : UserId,
  });
  const User = IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'role' : Role,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const ApiError = IDL.Variant({
    'notFound' : IDL.Null,
    'internalError' : IDL.Text,
    'unauthorized' : IDL.Null,
    'badRequest' : IDL.Text,
  });
  const Result_9 = IDL.Variant({ 'ok' : Document, 'err' : ApiError });
  const Result = IDL.Variant({ 'ok' : InventoryItem, 'err' : ApiError });
  const Result_8 = IDL.Variant({ 'ok' : Message, 'err' : ApiError });
  const Result_2 = IDL.Variant({ 'ok' : Booking, 'err' : ApiError });
  const Result_1 = IDL.Variant({
    'ok' : CoordinatorLocation,
    'err' : ApiError,
  });
  const Result_7 = IDL.Variant({ 'ok' : IDL.Vec(Document), 'err' : ApiError });
  const Result_6 = IDL.Variant({
    'ok' : IDL.Vec(InventoryItem),
    'err' : ApiError,
  });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Vec(Message), 'err' : ApiError });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Vec(Booking), 'err' : ApiError });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'role' : Role,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : UserProfile, 'err' : ApiError });
  const LoginInput = IDL.Record({ 'password' : IDL.Text, 'email' : IDL.Text });
  const RegisterInput = IDL.Record({
    'password' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    '__bookings' : IDL.Func(
        [IDL.Opt(BookingId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(BookingId, Booking))],
        ['query'],
      ),
    '__coordinatorLocations' : IDL.Func(
        [IDL.Opt(BookingId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(BookingId, CoordinatorLocation))],
        ['query'],
      ),
    '__documents' : IDL.Func(
        [IDL.Opt(DocumentId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(DocumentId, Document))],
        ['query'],
      ),
    '__inventoryItems' : IDL.Func(
        [IDL.Opt(InventoryItemId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(InventoryItemId, InventoryItem))],
        ['query'],
      ),
    '__messages' : IDL.Func(
        [IDL.Opt(MessageId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(MessageId, Message))],
        ['query'],
      ),
    '__nextBookingId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextDocumentId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextInventoryItemId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextMessageId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextUserId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__users' : IDL.Func(
        [IDL.Opt(UserId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(UserId, User))],
        ['query'],
      ),
    'addDocument' : IDL.Func(
        [BookingId, DocumentType, IDL.Text, IDL.Text],
        [Result_9],
        [],
      ),
    'addInventoryItem' : IDL.Func(
        [
          BookingId,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          Priority,
        ],
        [Result],
        [],
      ),
    'addMessage' : IDL.Func(
        [BookingId, IDL.Text, IDL.Vec(IDL.Text)],
        [Result_8],
        [],
      ),
    'cancelBooking' : IDL.Func([BookingId], [Result_2], []),
    'createBooking' : IDL.Func(
        [RetrievalType, Address, SafetyAssessment, Timestamp, IDL.Nat],
        [Result_2],
        [],
      ),
    'getBooking' : IDL.Func([BookingId], [Result_2], ['query']),
    'getCoordinatorLocation' : IDL.Func([BookingId], [Result_1], ['query']),
    'getDocuments' : IDL.Func([BookingId], [Result_7], ['query']),
    'getInventoryItems' : IDL.Func([BookingId], [Result_6], ['query']),
    'getMessages' : IDL.Func([BookingId], [Result_5], ['query']),
    'getMyBookings' : IDL.Func([], [Result_4], ['query']),
    'getUserProfile' : IDL.Func([], [Result_3], ['query']),
    'listBookings' : IDL.Func([], [Result_4], ['query']),
    'loginUser' : IDL.Func([LoginInput], [Result_3], []),
    'registerUser' : IDL.Func([RegisterInput], [Result_3], []),
    'updateBookingStatus' : IDL.Func(
        [BookingId, RetrievalStatus],
        [Result_2],
        [],
      ),
    'updateCoordinatorLocation' : IDL.Func(
        [BookingId, Location],
        [Result_1],
        [],
      ),
    'updateInventoryItem' : IDL.Func(
        [
          InventoryItemId,
          IDL.Record({
            'status' : IDL.Opt(ItemStatus),
            'photoUrls' : IDL.Opt(IDL.Vec(IDL.Text)),
            'name' : IDL.Opt(IDL.Text),
            'description' : IDL.Opt(IDL.Text),
            'notes' : IDL.Opt(IDL.Text),
            'estimatedValue' : IDL.Opt(IDL.Nat),
            'priority' : IDL.Opt(Priority),
            'condition' : IDL.Opt(ItemCondition),
          }),
        ],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };