/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'city' : string,
  'unit' : [] | [string],
  'gateCode' : [] | [string],
  'specialInstructions' : [] | [string],
  'state' : string,
}
export type ApiError = { 'notFound' : null } |
  { 'internalError' : string } |
  { 'unauthorized' : null } |
  { 'badRequest' : string };
export interface Booking {
  'id' : BookingId,
  'status' : RetrievalStatus,
  'paymentStatus' : PaymentStatus,
  'scheduledDate' : Timestamp,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'retrievalType' : RetrievalType,
  'updatedAt' : Timestamp,
  'pickupAddress' : Address,
  'totalAmount' : bigint,
  'safetyAssessment' : SafetyAssessment,
}
export type BookingId = bigint;
export interface CoordinatorLocation {
  'bookingId' : BookingId,
  'updatedAt' : Timestamp,
  'location' : Location,
}
export interface Document {
  'id' : DocumentId,
  'url' : string,
  'bookingId' : BookingId,
  'name' : string,
  'createdAt' : Timestamp,
  'docType' : DocumentType,
}
export type DocumentId = bigint;
export type DocumentType = { 'pdf' : null } |
  { 'report' : null } |
  { 'signature' : null } |
  { 'receipt' : null } |
  { 'other' : null } |
  { 'video' : null } |
  { 'photo' : null };
export interface InventoryItem {
  'id' : InventoryItemId,
  'status' : ItemStatus,
  'photoUrls' : Array<string>,
  'bookingId' : BookingId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : [] | [string],
  'notes' : [] | [string],
  'estimatedValue' : [] | [bigint],
  'priority' : Priority,
  'condition' : ItemCondition,
}
export type InventoryItemId = bigint;
export type ItemCondition = { 'damaged' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null } |
  { 'excellent' : null };
export type ItemStatus = { 'damaged' : null } |
  { 'disputed' : null } |
  { 'pending' : null } |
  { 'notRetrieved' : null } |
  { 'retrieved' : null };
export interface Location { 'lat' : number, 'lng' : number }
export interface LoginInput { 'password' : string, 'email' : string }
export interface Message {
  'id' : MessageId,
  'content' : string,
  'bookingId' : BookingId,
  'createdAt' : Timestamp,
  'senderRole' : Role,
  'attachments' : Array<string>,
  'senderId' : UserId,
}
export type MessageId = bigint;
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface RegisterInput {
  'password' : string,
  'email' : string,
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export type Result = { 'ok' : InventoryItem } |
  { 'err' : ApiError };
export type Result_1 = { 'ok' : CoordinatorLocation } |
  { 'err' : ApiError };
export type Result_2 = { 'ok' : Booking } |
  { 'err' : ApiError };
export type Result_3 = { 'ok' : UserProfile } |
  { 'err' : ApiError };
export type Result_4 = { 'ok' : Array<Booking> } |
  { 'err' : ApiError };
export type Result_5 = { 'ok' : Array<Message> } |
  { 'err' : ApiError };
export type Result_6 = { 'ok' : Array<InventoryItem> } |
  { 'err' : ApiError };
export type Result_7 = { 'ok' : Array<Document> } |
  { 'err' : ApiError };
export type Result_8 = { 'ok' : Message } |
  { 'err' : ApiError };
export type Result_9 = { 'ok' : Document } |
  { 'err' : ApiError };
export type RetrievalStatus = { 'closed' : null } |
  { 'reviewing' : null } |
  { 'documentationComplete' : null } |
  { 'arrived' : null } |
  { 'traveling' : null } |
  { 'requestReceived' : null } |
  { 'finished' : null } |
  { 'inProgress' : null } |
  { 'coordinatorAssigned' : null };
export type RetrievalType = { 'separation' : null } |
  { 'emergency' : null } |
  { 'propertyExchange' : null } |
  { 'storage' : null } |
  { 'familyConflict' : null } |
  { 'breakup' : null } |
  { 'roommate' : null };
export type Role = { 'admin' : null } |
  { 'customer' : null } |
  { 'staff' : null };
export interface SafetyAssessment {
  'potentialThreats' : boolean,
  'restrainingOrder' : boolean,
  'petsPresent' : boolean,
  'notes' : [] | [string],
  'policeInvolvement' : boolean,
  'childrenPresent' : boolean,
  'historyOfConflict' : boolean,
  'weaponsConcern' : boolean,
}
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : string,
  'passwordHash' : string,
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : string,
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export interface _SERVICE {
  '__bookings' : ActorMethod<
    [[] | [BookingId], [] | [bigint]],
    Array<[BookingId, Booking]>
  >,
  '__coordinatorLocations' : ActorMethod<
    [[] | [BookingId], [] | [bigint]],
    Array<[BookingId, CoordinatorLocation]>
  >,
  '__documents' : ActorMethod<
    [[] | [DocumentId], [] | [bigint]],
    Array<[DocumentId, Document]>
  >,
  '__inventoryItems' : ActorMethod<
    [[] | [InventoryItemId], [] | [bigint]],
    Array<[InventoryItemId, InventoryItem]>
  >,
  '__messages' : ActorMethod<
    [[] | [MessageId], [] | [bigint]],
    Array<[MessageId, Message]>
  >,
  '__nextBookingId' : ActorMethod<[], any>,
  '__nextDocumentId' : ActorMethod<[], any>,
  '__nextInventoryItemId' : ActorMethod<[], any>,
  '__nextMessageId' : ActorMethod<[], any>,
  '__nextUserId' : ActorMethod<[], any>,
  '__users' : ActorMethod<
    [[] | [UserId], [] | [bigint]],
    Array<[UserId, User]>
  >,
  'addDocument' : ActorMethod<
    [BookingId, DocumentType, string, string],
    Result_9
  >,
  'addInventoryItem' : ActorMethod<
    [BookingId, string, Array<string>, [] | [string], [] | [bigint], Priority],
    Result
  >,
  'addMessage' : ActorMethod<[BookingId, string, Array<string>], Result_8>,
  'cancelBooking' : ActorMethod<[BookingId], Result_2>,
  'createBooking' : ActorMethod<
    [RetrievalType, Address, SafetyAssessment, Timestamp, bigint],
    Result_2
  >,
  'getBooking' : ActorMethod<[BookingId], Result_2>,
  'getCoordinatorLocation' : ActorMethod<[BookingId], Result_1>,
  'getDocuments' : ActorMethod<[BookingId], Result_7>,
  'getInventoryItems' : ActorMethod<[BookingId], Result_6>,
  'getMessages' : ActorMethod<[BookingId], Result_5>,
  'getMyBookings' : ActorMethod<[], Result_4>,
  'getUserProfile' : ActorMethod<[], Result_3>,
  'listBookings' : ActorMethod<[], Result_4>,
  'loginUser' : ActorMethod<[LoginInput], Result_3>,
  'registerUser' : ActorMethod<[RegisterInput], Result_3>,
  'updateBookingStatus' : ActorMethod<[BookingId, RetrievalStatus], Result_2>,
  'updateCoordinatorLocation' : ActorMethod<[BookingId, Location], Result_1>,
  'updateInventoryItem' : ActorMethod<
    [
      InventoryItemId,
      {
        'status' : [] | [ItemStatus],
        'photoUrls' : [] | [Array<string>],
        'name' : [] | [string],
        'description' : [] | [string],
        'notes' : [] | [string],
        'estimatedValue' : [] | [bigint],
        'priority' : [] | [Priority],
        'condition' : [] | [ItemCondition],
      },
    ],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];