/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    lat: number;
    lng: number;
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: Booking;
} | {
    __kind__: "err";
    err: ApiError;
};
export interface Document {
    id: DocumentId;
    url: string;
    bookingId: BookingId;
    name: string;
    createdAt: Timestamp;
    docType: DocumentType;
}
export type Result_5 = {
    __kind__: "ok";
    ok: Array<Message>;
} | {
    __kind__: "err";
    err: ApiError;
};
export type Result_1 = {
    __kind__: "ok";
    ok: CoordinatorLocation;
} | {
    __kind__: "err";
    err: ApiError;
};
export type Result_4 = {
    __kind__: "ok";
    ok: Array<Booking>;
} | {
    __kind__: "err";
    err: ApiError;
};
export interface InventoryItem {
    id: InventoryItemId;
    status: ItemStatus;
    photoUrls: Array<string>;
    bookingId: BookingId;
    name: string;
    createdAt: Timestamp;
    description?: string;
    notes?: string;
    estimatedValue?: bigint;
    priority: Priority;
    condition: ItemCondition;
}
export type DocumentId = bigint;
export interface RegisterInput {
    password: string;
    email: string;
    phone: string;
    lastName: string;
    firstName: string;
}
export type Result_7 = {
    __kind__: "ok";
    ok: Array<Document>;
} | {
    __kind__: "err";
    err: ApiError;
};
export interface Booking {
    id: BookingId;
    status: RetrievalStatus;
    paymentStatus: PaymentStatus;
    scheduledDate: Timestamp;
    userId: UserId;
    createdAt: Timestamp;
    retrievalType: RetrievalType;
    updatedAt: Timestamp;
    pickupAddress: Address;
    totalAmount: bigint;
    safetyAssessment: SafetyAssessment;
}
export interface LoginInput {
    password: string;
    email: string;
}
export type BookingId = bigint;
export interface CoordinatorLocation {
    bookingId: BookingId;
    updatedAt: Timestamp;
    location: Location;
}
export type Result_6 = {
    __kind__: "ok";
    ok: Array<InventoryItem>;
} | {
    __kind__: "err";
    err: ApiError;
};
export interface User {
    id: UserId;
    createdAt: Timestamp;
    role: Role;
    email: string;
    passwordHash: string;
    phone: string;
    lastName: string;
    firstName: string;
}
export type Result_9 = {
    __kind__: "ok";
    ok: Document;
} | {
    __kind__: "err";
    err: ApiError;
};
export type InventoryItemId = bigint;
export type UserId = Principal;
export type Result = {
    __kind__: "ok";
    ok: InventoryItem;
} | {
    __kind__: "err";
    err: ApiError;
};
export type Result_3 = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: ApiError;
};
export type MessageId = bigint;
export type ApiError = {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "internalError";
    internalError: string;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} | {
    __kind__: "badRequest";
    badRequest: string;
};
export type Result_8 = {
    __kind__: "ok";
    ok: Message;
} | {
    __kind__: "err";
    err: ApiError;
};
export interface SafetyAssessment {
    potentialThreats: boolean;
    restrainingOrder: boolean;
    petsPresent: boolean;
    notes?: string;
    policeInvolvement: boolean;
    childrenPresent: boolean;
    historyOfConflict: boolean;
    weaponsConcern: boolean;
}
export interface Message {
    id: MessageId;
    content: string;
    bookingId: BookingId;
    createdAt: Timestamp;
    senderRole: Role;
    attachments: Array<string>;
    senderId: UserId;
}
export interface UserProfile {
    id: UserId;
    createdAt: Timestamp;
    role: Role;
    email: string;
    phone: string;
    lastName: string;
    firstName: string;
}
export interface Address {
    zip: string;
    street: string;
    city: string;
    unit?: string;
    gateCode?: string;
    specialInstructions?: string;
    state: string;
}
export enum DocumentType {
    pdf = "pdf",
    report = "report",
    signature = "signature",
    receipt = "receipt",
    other = "other",
    video = "video",
    photo = "photo"
}
export enum ItemCondition {
    damaged = "damaged",
    fair = "fair",
    good = "good",
    poor = "poor",
    excellent = "excellent"
}
export enum ItemStatus {
    damaged = "damaged",
    disputed = "disputed",
    pending = "pending",
    notRetrieved = "notRetrieved",
    retrieved = "retrieved"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    refunded = "refunded",
    failed = "failed"
}
export enum Priority {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum RetrievalStatus {
    closed = "closed",
    reviewing = "reviewing",
    documentationComplete = "documentationComplete",
    arrived = "arrived",
    traveling = "traveling",
    requestReceived = "requestReceived",
    finished = "finished",
    inProgress = "inProgress",
    coordinatorAssigned = "coordinatorAssigned"
}
export enum RetrievalType {
    separation = "separation",
    emergency = "emergency",
    propertyExchange = "propertyExchange",
    storage = "storage",
    familyConflict = "familyConflict",
    breakup = "breakup",
    roommate = "roommate"
}
export enum Role {
    admin = "admin",
    customer = "customer",
    staff = "staff"
}
export interface backendInterface {
    __bookings(ko: BookingId | null, count: bigint | null): Promise<Array<[BookingId, Booking]>>;
    __coordinatorLocations(ko: BookingId | null, count: bigint | null): Promise<Array<[BookingId, CoordinatorLocation]>>;
    __documents(ko: DocumentId | null, count: bigint | null): Promise<Array<[DocumentId, Document]>>;
    __inventoryItems(ko: InventoryItemId | null, count: bigint | null): Promise<Array<[InventoryItemId, InventoryItem]>>;
    __messages(ko: MessageId | null, count: bigint | null): Promise<Array<[MessageId, Message]>>;
    __nextBookingId(): Promise<any>;
    __nextDocumentId(): Promise<any>;
    __nextInventoryItemId(): Promise<any>;
    __nextMessageId(): Promise<any>;
    __nextUserId(): Promise<any>;
    __users(ko: UserId | null, count: bigint | null): Promise<Array<[UserId, User]>>;
    addDocument(bookingId: BookingId, docType: DocumentType, url: string, name: string): Promise<Result_9>;
    addInventoryItem(bookingId: BookingId, name: string, photoUrls: Array<string>, description: string | null, estimatedValue: bigint | null, priority: Priority): Promise<Result>;
    addMessage(bookingId: BookingId, content: string, attachments: Array<string>): Promise<Result_8>;
    cancelBooking(id: BookingId): Promise<Result_2>;
    createBooking(retrievalType: RetrievalType, pickupAddress: Address, safetyAssessment: SafetyAssessment, scheduledDate: Timestamp, totalAmount: bigint): Promise<Result_2>;
    getBooking(id: BookingId): Promise<Result_2>;
    getCoordinatorLocation(bookingId: BookingId): Promise<Result_1>;
    getDocuments(bookingId: BookingId): Promise<Result_7>;
    getInventoryItems(bookingId: BookingId): Promise<Result_6>;
    getMessages(bookingId: BookingId): Promise<Result_5>;
    getMyBookings(): Promise<Result_4>;
    getUserProfile(): Promise<Result_3>;
    listBookings(): Promise<Result_4>;
    loginUser(input: LoginInput): Promise<Result_3>;
    registerUser(input: RegisterInput): Promise<Result_3>;
    updateBookingStatus(id: BookingId, status: RetrievalStatus): Promise<Result_2>;
    updateCoordinatorLocation(bookingId: BookingId, location: Location): Promise<Result_1>;
    updateInventoryItem(id: InventoryItemId, updates: {
        status?: ItemStatus;
        photoUrls?: Array<string>;
        name?: string;
        description?: string;
        notes?: string;
        estimatedValue?: bigint;
        priority?: Priority;
        condition?: ItemCondition;
    }): Promise<Result>;
}
import type { Address as _Address, ApiError as _ApiError, Booking as _Booking, BookingId as _BookingId, CoordinatorLocation as _CoordinatorLocation, Document as _Document, DocumentId as _DocumentId, DocumentType as _DocumentType, InventoryItem as _InventoryItem, InventoryItemId as _InventoryItemId, ItemCondition as _ItemCondition, ItemStatus as _ItemStatus, Message as _Message, MessageId as _MessageId, PaymentStatus as _PaymentStatus, Priority as _Priority, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, RetrievalStatus as _RetrievalStatus, RetrievalType as _RetrievalType, Role as _Role, SafetyAssessment as _SafetyAssessment, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __bookings(arg0: BookingId | null, arg1: bigint | null): Promise<Array<[BookingId, Booking]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__bookings(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__bookings(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async __coordinatorLocations(arg0: BookingId | null, arg1: bigint | null): Promise<Array<[BookingId, CoordinatorLocation]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__coordinatorLocations(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__coordinatorLocations(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __documents(arg0: DocumentId | null, arg1: bigint | null): Promise<Array<[DocumentId, Document]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__documents(to_candid_opt_n18(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__documents(to_candid_opt_n18(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async __inventoryItems(arg0: InventoryItemId | null, arg1: bigint | null): Promise<Array<[InventoryItemId, InventoryItem]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__inventoryItems(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__inventoryItems(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async __messages(arg0: MessageId | null, arg1: bigint | null): Promise<Array<[MessageId, Message]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__messages(to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__messages(to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async __nextBookingId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextBookingId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextBookingId();
            return result;
        }
    }
    async __nextDocumentId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextDocumentId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextDocumentId();
            return result;
        }
    }
    async __nextInventoryItemId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextInventoryItemId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextInventoryItemId();
            return result;
        }
    }
    async __nextMessageId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextMessageId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextMessageId();
            return result;
        }
    }
    async __nextUserId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextUserId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextUserId();
            return result;
        }
    }
    async __users(arg0: UserId | null, arg1: bigint | null): Promise<Array<[UserId, User]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__users(to_candid_opt_n44(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__users(to_candid_opt_n44(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async addDocument(arg0: BookingId, arg1: DocumentType, arg2: string, arg3: string): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(arg0, to_candid_DocumentType_n49(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_Result_9_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(arg0, to_candid_DocumentType_n49(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_Result_9_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async addInventoryItem(arg0: BookingId, arg1: string, arg2: Array<string>, arg3: string | null, arg4: bigint | null, arg5: Priority): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryItem(arg0, arg1, arg2, to_candid_opt_n55(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg4), to_candid_Priority_n56(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Result_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryItem(arg0, arg1, arg2, to_candid_opt_n55(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg4), to_candid_Priority_n56(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Result_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async addMessage(arg0: BookingId, arg1: string, arg2: Array<string>): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, arg1, arg2);
                return from_candid_Result_8_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, arg1, arg2);
            return from_candid_Result_8_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelBooking(arg0: BookingId): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return from_candid_Result_2_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return from_candid_Result_2_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBooking(arg0: RetrievalType, arg1: Address, arg2: SafetyAssessment, arg3: Timestamp, arg4: bigint): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_RetrievalType_n64(this._uploadFile, this._downloadFile, arg0), to_candid_Address_n66(this._uploadFile, this._downloadFile, arg1), to_candid_SafetyAssessment_n68(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_Result_2_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_RetrievalType_n64(this._uploadFile, this._downloadFile, arg0), to_candid_Address_n66(this._uploadFile, this._downloadFile, arg1), to_candid_SafetyAssessment_n68(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_Result_2_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: BookingId): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_Result_2_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_Result_2_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoordinatorLocation(arg0: BookingId): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoordinatorLocation(arg0);
                return from_candid_Result_1_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoordinatorLocation(arg0);
            return from_candid_Result_1_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocuments(arg0: BookingId): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocuments(arg0);
                return from_candid_Result_7_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocuments(arg0);
            return from_candid_Result_7_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryItems(arg0: BookingId): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItems(arg0);
                return from_candid_Result_6_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItems(arg0);
            return from_candid_Result_6_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: BookingId): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return from_candid_Result_5_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return from_candid_Result_5_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_Result_4_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_Result_4_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_Result_3_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_Result_3_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBookings(): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.listBookings();
                return from_candid_Result_4_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBookings();
            return from_candid_Result_4_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginUser(arg0: LoginInput): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0);
                return from_candid_Result_3_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0);
            return from_candid_Result_3_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: RegisterInput): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return from_candid_Result_3_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return from_candid_Result_3_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBookingStatus(arg0: BookingId, arg1: RetrievalStatus): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_RetrievalStatus_n88(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_2_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_RetrievalStatus_n88(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_2_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCoordinatorLocation(arg0: BookingId, arg1: Location): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoordinatorLocation(arg0, arg1);
                return from_candid_Result_1_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoordinatorLocation(arg0, arg1);
            return from_candid_Result_1_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInventoryItem(arg0: InventoryItemId, arg1: {
        status?: ItemStatus;
        photoUrls?: Array<string>;
        name?: string;
        description?: string;
        notes?: string;
        estimatedValue?: bigint;
        priority?: Priority;
        condition?: ItemCondition;
    }): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0, to_candid_record_n90(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0, to_candid_record_n90(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n58(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Address_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Address): Address {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ApiError_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiError): ApiError {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentType): DocumentType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Document_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Document {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryItem_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryItem): InventoryItem {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ItemCondition_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemCondition): ItemCondition {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ItemStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemStatus): ItemStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n85(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n82(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n79(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function from_candid_Result_8_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_8): Result_8 {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Result_9_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_9): Result_9 {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_RetrievalStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RetrievalStatus): RetrievalStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RetrievalType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RetrievalType): RetrievalType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_SafetyAssessment_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SafetyAssessment): SafetyAssessment {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n87(_uploadFile, _downloadFile, value);
}
function from_candid_User_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    zip: string;
    street: string;
    city: string;
    unit: [] | [string];
    gateCode: [] | [string];
    specialInstructions: [] | [string];
    state: string;
}): {
    zip: string;
    street: string;
    city: string;
    unit?: string;
    gateCode?: string;
    specialInstructions?: string;
    state: string;
} {
    return {
        zip: value.zip,
        street: value.street,
        city: value.city,
        unit: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.unit)),
        gateCode: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.gateCode)),
        specialInstructions: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.specialInstructions)),
        state: value.state
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    potentialThreats: boolean;
    restrainingOrder: boolean;
    petsPresent: boolean;
    notes: [] | [string];
    policeInvolvement: boolean;
    childrenPresent: boolean;
    historyOfConflict: boolean;
    weaponsConcern: boolean;
}): {
    potentialThreats: boolean;
    restrainingOrder: boolean;
    petsPresent: boolean;
    notes?: string;
    policeInvolvement: boolean;
    childrenPresent: boolean;
    historyOfConflict: boolean;
    weaponsConcern: boolean;
} {
    return {
        potentialThreats: value.potentialThreats,
        restrainingOrder: value.restrainingOrder,
        petsPresent: value.petsPresent,
        notes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.notes)),
        policeInvolvement: value.policeInvolvement,
        childrenPresent: value.childrenPresent,
        historyOfConflict: value.historyOfConflict,
        weaponsConcern: value.weaponsConcern
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DocumentId;
    url: string;
    bookingId: _BookingId;
    name: string;
    createdAt: _Timestamp;
    docType: _DocumentType;
}): {
    id: DocumentId;
    url: string;
    bookingId: BookingId;
    name: string;
    createdAt: Timestamp;
    docType: DocumentType;
} {
    return {
        id: value.id,
        url: value.url,
        bookingId: value.bookingId,
        name: value.name,
        createdAt: value.createdAt,
        docType: from_candid_DocumentType_n23(_uploadFile, _downloadFile, value.docType)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InventoryItemId;
    status: _ItemStatus;
    photoUrls: Array<string>;
    bookingId: _BookingId;
    name: string;
    createdAt: _Timestamp;
    description: [] | [string];
    notes: [] | [string];
    estimatedValue: [] | [bigint];
    priority: _Priority;
    condition: _ItemCondition;
}): {
    id: InventoryItemId;
    status: ItemStatus;
    photoUrls: Array<string>;
    bookingId: BookingId;
    name: string;
    createdAt: Timestamp;
    description?: string;
    notes?: string;
    estimatedValue?: bigint;
    priority: Priority;
    condition: ItemCondition;
} {
    return {
        id: value.id,
        status: from_candid_ItemStatus_n30(_uploadFile, _downloadFile, value.status),
        photoUrls: value.photoUrls,
        bookingId: value.bookingId,
        name: value.name,
        createdAt: value.createdAt,
        description: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.description)),
        notes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.notes)),
        estimatedValue: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.estimatedValue)),
        priority: from_candid_Priority_n33(_uploadFile, _downloadFile, value.priority),
        condition: from_candid_ItemCondition_n35(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    content: string;
    bookingId: _BookingId;
    createdAt: _Timestamp;
    senderRole: _Role;
    attachments: Array<string>;
    senderId: _UserId;
}): {
    id: MessageId;
    content: string;
    bookingId: BookingId;
    createdAt: Timestamp;
    senderRole: Role;
    attachments: Array<string>;
    senderId: UserId;
} {
    return {
        id: value.id,
        content: value.content,
        bookingId: value.bookingId,
        createdAt: value.createdAt,
        senderRole: from_candid_Role_n42(_uploadFile, _downloadFile, value.senderRole),
        attachments: value.attachments,
        senderId: value.senderId
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    createdAt: _Timestamp;
    role: _Role;
    email: string;
    passwordHash: string;
    phone: string;
    lastName: string;
    firstName: string;
}): {
    id: UserId;
    createdAt: Timestamp;
    role: Role;
    email: string;
    passwordHash: string;
    phone: string;
    lastName: string;
    firstName: string;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        role: from_candid_Role_n42(_uploadFile, _downloadFile, value.role),
        email: value.email,
        passwordHash: value.passwordHash,
        phone: value.phone,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    status: _RetrievalStatus;
    paymentStatus: _PaymentStatus;
    scheduledDate: _Timestamp;
    userId: _UserId;
    createdAt: _Timestamp;
    retrievalType: _RetrievalType;
    updatedAt: _Timestamp;
    pickupAddress: _Address;
    totalAmount: bigint;
    safetyAssessment: _SafetyAssessment;
}): {
    id: BookingId;
    status: RetrievalStatus;
    paymentStatus: PaymentStatus;
    scheduledDate: Timestamp;
    userId: UserId;
    createdAt: Timestamp;
    retrievalType: RetrievalType;
    updatedAt: Timestamp;
    pickupAddress: Address;
    totalAmount: bigint;
    safetyAssessment: SafetyAssessment;
} {
    return {
        id: value.id,
        status: from_candid_RetrievalStatus_n7(_uploadFile, _downloadFile, value.status),
        paymentStatus: from_candid_PaymentStatus_n9(_uploadFile, _downloadFile, value.paymentStatus),
        scheduledDate: value.scheduledDate,
        userId: value.userId,
        createdAt: value.createdAt,
        retrievalType: from_candid_RetrievalType_n11(_uploadFile, _downloadFile, value.retrievalType),
        updatedAt: value.updatedAt,
        pickupAddress: from_candid_Address_n13(_uploadFile, _downloadFile, value.pickupAddress),
        totalAmount: value.totalAmount,
        safetyAssessment: from_candid_SafetyAssessment_n16(_uploadFile, _downloadFile, value.safetyAssessment)
    };
}
function from_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    createdAt: _Timestamp;
    role: _Role;
    email: string;
    phone: string;
    lastName: string;
    firstName: string;
}): {
    id: UserId;
    createdAt: Timestamp;
    role: Role;
    email: string;
    phone: string;
    lastName: string;
    firstName: string;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        role: from_candid_Role_n42(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_tuple_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_DocumentId, _Document]): [DocumentId, Document] {
    return [
        value[0],
        from_candid_Document_n21(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_InventoryItemId, _InventoryItem]): [InventoryItemId, InventoryItem] {
    return [
        value[0],
        from_candid_InventoryItem_n28(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_MessageId, _Message]): [MessageId, Message] {
    return [
        value[0],
        from_candid_Message_n40(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_BookingId, _Booking]): [BookingId, Booking] {
    return [
        value[0],
        from_candid_Booking_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_UserId, _User]): [UserId, User] {
    return [
        value[0],
        from_candid_User_n47(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "refunded" in value ? PaymentStatus.refunded : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    separation: null;
} | {
    emergency: null;
} | {
    propertyExchange: null;
} | {
    storage: null;
} | {
    familyConflict: null;
} | {
    breakup: null;
} | {
    roommate: null;
}): RetrievalType {
    return "separation" in value ? RetrievalType.separation : "emergency" in value ? RetrievalType.emergency : "propertyExchange" in value ? RetrievalType.propertyExchange : "storage" in value ? RetrievalType.storage : "familyConflict" in value ? RetrievalType.familyConflict : "breakup" in value ? RetrievalType.breakup : "roommate" in value ? RetrievalType.roommate : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: null;
} | {
    report: null;
} | {
    signature: null;
} | {
    receipt: null;
} | {
    other: null;
} | {
    video: null;
} | {
    photo: null;
}): DocumentType {
    return "pdf" in value ? DocumentType.pdf : "report" in value ? DocumentType.report : "signature" in value ? DocumentType.signature : "receipt" in value ? DocumentType.receipt : "other" in value ? DocumentType.other : "video" in value ? DocumentType.video : "photo" in value ? DocumentType.photo : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    damaged: null;
} | {
    disputed: null;
} | {
    pending: null;
} | {
    notRetrieved: null;
} | {
    retrieved: null;
}): ItemStatus {
    return "damaged" in value ? ItemStatus.damaged : "disputed" in value ? ItemStatus.disputed : "pending" in value ? ItemStatus.pending : "notRetrieved" in value ? ItemStatus.notRetrieved : "retrieved" in value ? ItemStatus.retrieved : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "critical" in value ? Priority.critical : "medium" in value ? Priority.medium : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    damaged: null;
} | {
    fair: null;
} | {
    good: null;
} | {
    poor: null;
} | {
    excellent: null;
}): ItemCondition {
    return "damaged" in value ? ItemCondition.damaged : "fair" in value ? ItemCondition.fair : "good" in value ? ItemCondition.good : "poor" in value ? ItemCondition.poor : "excellent" in value ? ItemCondition.excellent : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customer: null;
} | {
    staff: null;
}): Role {
    return "admin" in value ? Role.admin : "customer" in value ? Role.customer : "staff" in value ? Role.staff : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Document;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: Document;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Document_n21(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n53(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notFound: null;
} | {
    internalError: string;
} | {
    unauthorized: null;
} | {
    badRequest: string;
}): {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "internalError";
    internalError: string;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} | {
    __kind__: "badRequest";
    badRequest: string;
} {
    return "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "internalError" in value ? {
        __kind__: "internalError",
        internalError: value.internalError
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : "badRequest" in value ? {
        __kind__: "badRequest",
        badRequest: value.badRequest
    } : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _InventoryItem;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: InventoryItem;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_InventoryItem_n28(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n53(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Message;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: Message;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Message_n40(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n53(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Booking;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: Booking;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Booking_n5(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n53(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CoordinatorLocation;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: CoordinatorLocation;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n53(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Document>;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: Array<Document>;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n74(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n53(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_InventoryItem>;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: Array<InventoryItem>;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n77(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n53(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Message>;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: Array<Message>;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n80(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n53(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    reviewing: null;
} | {
    documentationComplete: null;
} | {
    arrived: null;
} | {
    traveling: null;
} | {
    requestReceived: null;
} | {
    finished: null;
} | {
    inProgress: null;
} | {
    coordinatorAssigned: null;
}): RetrievalStatus {
    return "closed" in value ? RetrievalStatus.closed : "reviewing" in value ? RetrievalStatus.reviewing : "documentationComplete" in value ? RetrievalStatus.documentationComplete : "arrived" in value ? RetrievalStatus.arrived : "traveling" in value ? RetrievalStatus.traveling : "requestReceived" in value ? RetrievalStatus.requestReceived : "finished" in value ? RetrievalStatus.finished : "inProgress" in value ? RetrievalStatus.inProgress : "coordinatorAssigned" in value ? RetrievalStatus.coordinatorAssigned : value;
}
function from_candid_variant_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Booking>;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: Array<Booking>;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n83(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n53(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n86(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n53(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_DocumentId, _Document]>): Array<[DocumentId, Document]> {
    return value.map((x)=>from_candid_tuple_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_InventoryItemId, _InventoryItem]>): Array<[InventoryItemId, InventoryItem]> {
    return value.map((x)=>from_candid_tuple_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_BookingId, _Booking]>): Array<[BookingId, Booking]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_MessageId, _Message]>): Array<[MessageId, Message]> {
    return value.map((x)=>from_candid_tuple_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_UserId, _User]>): Array<[UserId, User]> {
    return value.map((x)=>from_candid_tuple_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Array<Document> {
    return value.map((x)=>from_candid_Document_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryItem>): Array<InventoryItem> {
    return value.map((x)=>from_candid_InventoryItem_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n5(_uploadFile, _downloadFile, x));
}
function to_candid_Address_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Address): _Address {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentType_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): _DocumentType {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_ItemCondition_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemCondition): _ItemCondition {
    return to_candid_variant_n94(_uploadFile, _downloadFile, value);
}
function to_candid_ItemStatus_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemStatus): _ItemStatus {
    return to_candid_variant_n92(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_RetrievalStatus_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RetrievalStatus): _RetrievalStatus {
    return to_candid_variant_n89(_uploadFile, _downloadFile, value);
}
function to_candid_RetrievalType_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RetrievalType): _RetrievalType {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_SafetyAssessment_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SafetyAssessment): _SafetyAssessment {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingId | null): [] | [_BookingId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentId | null): [] | [_DocumentId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryItemId | null): [] | [_InventoryItemId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageId | null): [] | [_MessageId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    zip: string;
    street: string;
    city: string;
    unit?: string;
    gateCode?: string;
    specialInstructions?: string;
    state: string;
}): {
    zip: string;
    street: string;
    city: string;
    unit: [] | [string];
    gateCode: [] | [string];
    specialInstructions: [] | [string];
    state: string;
} {
    return {
        zip: value.zip,
        street: value.street,
        city: value.city,
        unit: value.unit ? candid_some(value.unit) : candid_none(),
        gateCode: value.gateCode ? candid_some(value.gateCode) : candid_none(),
        specialInstructions: value.specialInstructions ? candid_some(value.specialInstructions) : candid_none(),
        state: value.state
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    potentialThreats: boolean;
    restrainingOrder: boolean;
    petsPresent: boolean;
    notes?: string;
    policeInvolvement: boolean;
    childrenPresent: boolean;
    historyOfConflict: boolean;
    weaponsConcern: boolean;
}): {
    potentialThreats: boolean;
    restrainingOrder: boolean;
    petsPresent: boolean;
    notes: [] | [string];
    policeInvolvement: boolean;
    childrenPresent: boolean;
    historyOfConflict: boolean;
    weaponsConcern: boolean;
} {
    return {
        potentialThreats: value.potentialThreats,
        restrainingOrder: value.restrainingOrder,
        petsPresent: value.petsPresent,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        policeInvolvement: value.policeInvolvement,
        childrenPresent: value.childrenPresent,
        historyOfConflict: value.historyOfConflict,
        weaponsConcern: value.weaponsConcern
    };
}
function to_candid_record_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: ItemStatus;
    photoUrls?: Array<string>;
    name?: string;
    description?: string;
    notes?: string;
    estimatedValue?: bigint;
    priority?: Priority;
    condition?: ItemCondition;
}): {
    status: [] | [_ItemStatus];
    photoUrls: [] | [Array<string>];
    name: [] | [string];
    description: [] | [string];
    notes: [] | [string];
    estimatedValue: [] | [bigint];
    priority: [] | [_Priority];
    condition: [] | [_ItemCondition];
} {
    return {
        status: value.status ? candid_some(to_candid_ItemStatus_n91(_uploadFile, _downloadFile, value.status)) : candid_none(),
        photoUrls: value.photoUrls ? candid_some(value.photoUrls) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        estimatedValue: value.estimatedValue ? candid_some(value.estimatedValue) : candid_none(),
        priority: value.priority ? candid_some(to_candid_Priority_n56(_uploadFile, _downloadFile, value.priority)) : candid_none(),
        condition: value.condition ? candid_some(to_candid_ItemCondition_n93(_uploadFile, _downloadFile, value.condition)) : candid_none()
    };
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): {
    pdf: null;
} | {
    report: null;
} | {
    signature: null;
} | {
    receipt: null;
} | {
    other: null;
} | {
    video: null;
} | {
    photo: null;
} {
    return value == DocumentType.pdf ? {
        pdf: null
    } : value == DocumentType.report ? {
        report: null
    } : value == DocumentType.signature ? {
        signature: null
    } : value == DocumentType.receipt ? {
        receipt: null
    } : value == DocumentType.other ? {
        other: null
    } : value == DocumentType.video ? {
        video: null
    } : value == DocumentType.photo ? {
        photo: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.critical ? {
        critical: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RetrievalType): {
    separation: null;
} | {
    emergency: null;
} | {
    propertyExchange: null;
} | {
    storage: null;
} | {
    familyConflict: null;
} | {
    breakup: null;
} | {
    roommate: null;
} {
    return value == RetrievalType.separation ? {
        separation: null
    } : value == RetrievalType.emergency ? {
        emergency: null
    } : value == RetrievalType.propertyExchange ? {
        propertyExchange: null
    } : value == RetrievalType.storage ? {
        storage: null
    } : value == RetrievalType.familyConflict ? {
        familyConflict: null
    } : value == RetrievalType.breakup ? {
        breakup: null
    } : value == RetrievalType.roommate ? {
        roommate: null
    } : value;
}
function to_candid_variant_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RetrievalStatus): {
    closed: null;
} | {
    reviewing: null;
} | {
    documentationComplete: null;
} | {
    arrived: null;
} | {
    traveling: null;
} | {
    requestReceived: null;
} | {
    finished: null;
} | {
    inProgress: null;
} | {
    coordinatorAssigned: null;
} {
    return value == RetrievalStatus.closed ? {
        closed: null
    } : value == RetrievalStatus.reviewing ? {
        reviewing: null
    } : value == RetrievalStatus.documentationComplete ? {
        documentationComplete: null
    } : value == RetrievalStatus.arrived ? {
        arrived: null
    } : value == RetrievalStatus.traveling ? {
        traveling: null
    } : value == RetrievalStatus.requestReceived ? {
        requestReceived: null
    } : value == RetrievalStatus.finished ? {
        finished: null
    } : value == RetrievalStatus.inProgress ? {
        inProgress: null
    } : value == RetrievalStatus.coordinatorAssigned ? {
        coordinatorAssigned: null
    } : value;
}
function to_candid_variant_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemStatus): {
    damaged: null;
} | {
    disputed: null;
} | {
    pending: null;
} | {
    notRetrieved: null;
} | {
    retrieved: null;
} {
    return value == ItemStatus.damaged ? {
        damaged: null
    } : value == ItemStatus.disputed ? {
        disputed: null
    } : value == ItemStatus.pending ? {
        pending: null
    } : value == ItemStatus.notRetrieved ? {
        notRetrieved: null
    } : value == ItemStatus.retrieved ? {
        retrieved: null
    } : value;
}
function to_candid_variant_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemCondition): {
    damaged: null;
} | {
    fair: null;
} | {
    good: null;
} | {
    poor: null;
} | {
    excellent: null;
} {
    return value == ItemCondition.damaged ? {
        damaged: null
    } : value == ItemCondition.fair ? {
        fair: null
    } : value == ItemCondition.good ? {
        good: null
    } : value == ItemCondition.poor ? {
        poor: null
    } : value == ItemCondition.excellent ? {
        excellent: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
